# Site settings
name: Less Or More
email: weirdoyinke@gmail.com
author: Yin, Ke
url: 
resume_site: 
github: https://github.com/echoyinke
baseurl: 
description: Actually, less is more!
meta_description: 皮中带稳;稳中带皮;生命不止;折腾不休。
motto: 
banner: 面对疾风吧！

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: echoyinke
highlighter: Pygments

# Build settings
markdown: kramdown


FB:
  comments :
    provider : yungentie
    duoshuo:
        short_name : 
    disqus :
        short_name : 
   
